### ISSUE TITLE
License violation

### ISSUE THREAD

**Issue by benschwarz** [crush-pics/crush-pics-github-action#4]
With this project you've lifted code, design and documentation from @calibreapp/image-actions without any form of attribution of the original license. It's then been relabeled as your original work. 

Not only is this not in the spirit of open source, it's against the license. 

### References

* [The commit](https://github.com/crush-pics/crush-pics-github-action/commit/b49fc60e7b5aabacfc5b20f8053d3629869d7115) that included the README from @calibreapp/image-actions
* [Portions of code](https://github.com/crush-pics/crush-pics-github-action/blob/master/src/github.js) have been directly copied with renamed variables
* @thatdom [first forked our repo](https://user-images.githubusercontent.com/924/73985674-ec30e600-498f-11ea-9018-94cacd0ac8ac.png)

Are you able to explain? @thatdom @m0n9oose

**Comment by thatdom** [comment]
I am sorry you feel that way, but it's completely unfair to characterise this as a *"lifting code, design and documentation"*. If you look into source code, you can see that we used only one small part of your code - like you mention - to create GitHub commit and comment. Everything else is our own code.

Besides that, this action is working in a completely different way then your "Image Actions", this action is compressing images by sending them to HTTP API, where your script is using local binaries to perform compression.

All that said, we should have put attribution (no matter how big or small code we used is), in our licence and we fixed that mistake now.
